apiVersion: apps/v1
kind: Deployment
metadata: 
  name: second-app
spec:
  revisionHistoryLimit: 5
  replicas: 3
  selector:
    matchLabels:
      app: second-kube
  template: 
    metadata:
      labels:
        app: second-kube
    spec: 
      containers: 
        - name: second-kube
          image: inovusniklas/kube:3
