apiVersion: v1
kind: Service
metadata: 
  name: second-kube-service

spec:
  selector: 
    app: second-kube
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080 
      name: pipe
  type: LoadBalancer